### Computing numerical inverse

In [1]:
import numpy as np

In [4]:
A = np.array([[4, -2, 1],[3, 6, -4], [2, 1, 8]])

In [6]:
A_inv = np.linalg.inv(A)

In [7]:
A_inv

array([[ 0.19771863,  0.06463878,  0.00760456],
       [-0.121673  ,  0.11406844,  0.07224335],
       [-0.03422053, -0.03041825,  0.11406844]])

In [8]:
print(np.dot(A_inv,A))

[[ 1.00000000e+00 -1.04083409e-17  0.00000000e+00]
 [ 8.32667268e-17  1.00000000e+00 -1.11022302e-16]
 [ 2.77555756e-17  0.00000000e+00  1.00000000e+00]]


In [9]:
print(np.dot(A,A_inv))

[[ 1.00000000e+00 -1.38777878e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -5.55111512e-17]
 [ 5.55111512e-17  2.77555756e-17  1.00000000e+00]]


In [10]:
true_inv=1/263* np.array([[52, 17, 2],[-32, 30, 19],[-9, -8,30]])

In [11]:
true_inv

array([[ 0.19771863,  0.06463878,  0.00760456],
       [-0.121673  ,  0.11406844,  0.07224335],
       [-0.03422053, -0.03041825,  0.11406844]])

### Solving linear equations simultaneously

In [12]:
A = np.array([[4, -2, 1],[3, 6, -4], [2, 1, 8]])

In [13]:
B = np.array([[12,4,20],[-25,-10,-30],[32,22,40]])

In [14]:
X = np.linalg.solve(A,B)

In [15]:
X

array([[ 1.        ,  0.31178707,  2.31939163],
       [-2.        , -0.03802281, -2.96577947],
       [ 4.        ,  2.67680608,  4.79087452]])

### Computing Eigenvalues and Eigenvectors
Check if a skew symmetric matrix has complex conjugate eigenvectors and eigenvalues

In [17]:
A = np.array([[1,2],[-2,1]])

In [22]:
Lambda = np.linalg.eigvals(A) #computes eigenvalues

In [23]:
Lambda

array([1.+2.j, 1.-2.j])

In [28]:
Lambda,V = np.linalg.eig(A) # computes eigenvalues and right eigenvectors of matrix

In [29]:
V

array([[0.        -0.70710678j, 0.        +0.70710678j],
       [0.70710678+0.j        , 0.70710678-0.j        ]])

### Eigenvalues with algebraic multiplicity

In [30]:
A = np.array([[-2, 2, -3],[2,1,-6],[-1,-2,0]])

In [35]:
eigenvalues,eigenvectors = np.linalg.eig(A)

In [36]:
eigenvalues

array([-3.,  5., -3.])

In [37]:
eigenvectors

array([[-0.95257934,  0.40824829, -0.02296692],
       [ 0.27216553,  0.81649658,  0.83534731],
       [-0.13608276, -0.40824829,  0.54924256]])

In [38]:
ev2 = eigenvectors[:,1] # eigenvrctor corresponding to eigenvalue 5

In [39]:
ev2

array([ 0.40824829,  0.81649658, -0.40824829])

In [44]:
analytic_ev2 = 1/np.sqrt(6)*np.array([-1,-2,1])
analytic_ev2

array([-0.40824829, -0.81649658,  0.40824829])

In [42]:
ratio = ev2 /analytic_ev2

In [43]:
ratio

array([-1., -1., -1.])

### Hilbert Matrix

In [51]:
import scipy.linalg

In [52]:
hilbert_matrix = scipy.linalg.hilbert(100)

In [53]:
b = hilbert_matrix[:,0]

In [54]:
x = np.linalg.solve(hilbert_matrix,b)

In [55]:
x

array([ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0., -0., -0.,  0.,  0.,
        0., -0.,  0., -0., -0.,  0., -0.,  0.,  0.,  0., -0.,  0.,  0.,
       -0.,  0.,  0., -0., -0.,  0.,  0., -0., -0., -0.,  0., -0.,  0.,
        0., -0., -0.,  0.,  0.,  0.,  0.,  0., -0.,  0., -0.,  0., -0.,
        0.,  0.,  0., -0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0., -0., -0., -0.,  0.,  0., -0.,  0., -0.,  0., -0.,  0.,
        0.,  0.,  0.,  0., -0.,  0., -0., -0., -0., -0.,  0., -0.,  0.,
        0., -0.,  0.,  0.,  0., -0., -0.,  0.,  0.])

### Dirac Gamma Matrix
The Dirac equation extends quantum mechanics to
include relativity and spin $1/2$. The extension of the Hamiltonian operator for
an electron requires it to contain matrices, and those matrices are expressed
in terms of $4 \times 4$ $\gamma$ matrices that can be represented in terms of the familiar
2 × 2 Pauli matrices $\sigma_i$:

In [60]:
gamma1 = np.array([[0,0,0,1],[0,0,1,0],[0,-1,0,0],[-1,0,0,0]])
gamma1

array([[ 0,  0,  0,  1],
       [ 0,  0,  1,  0],
       [ 0, -1,  0,  0],
       [-1,  0,  0,  0]])

In [61]:
gamma2 = np.array([[0,0,0,np.complex(0,-1)],[0,0,np.complex(0,1),0],[0,np.complex(0,1),0,0],[np.complex(0,-1),0,0,0]], dtype = np.complex)
gamma2

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.-1.j],
       [0.+0.j, 0.+0.j, 0.+1.j, 0.+0.j],
       [0.+0.j, 0.+1.j, 0.+0.j, 0.+0.j],
       [0.-1.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [62]:
gamma3 = np.array([[0,0,1,0],[0,0,0,-1],[-1,0,0,0],[0,1,0,0]])
gamma3

array([[ 0,  0,  1,  0],
       [ 0,  0,  0, -1],
       [-1,  0,  0,  0],
       [ 0,  1,  0,  0]])

In [64]:
gamma2_inv = np.linalg.inv(gamma2)
gamma2_inv+gamma2 #gamma_2^(-1) = -gamma_2

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [69]:
np.complex(0,-1)*np.array([[1,0,0,0],[0,-1,0,0],[0,0,1,0],[0,0,0,-1]])

array([[0.-1.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+1.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.-1.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+1.j]])

In [68]:
np.dot(gamma1,gamma2)

array([[0.-1.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+1.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.-1.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+1.j]])